name: PetClinic CI/CD

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  integration-continue:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilation
        run: mvn compile

      - name: Tests unitaires
        run: mvn test

      - name: Analyse de qualité et sécurité (PMD)
        run: mvn pmd:check
        continue-on-error: true